export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const CREATE_PAYMENT_LINK_REQUEST = 'CREATE_PAYMENT_LINK_REQUEST';
export const CREATE_PAYMENT_LINK_FAILURE = 'CREATE_PAYMENT_LINK_FAILURE';